AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10
    MemorySize: 256

Resources:
  ServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bootstrap
      Runtime: provided.al2 # Recommended for Go
      Architectures:
        - x86_64
      Environment:
        Variables:
          # Tell ADOT to use the default config or a custom one
          OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /var/task/otel-config.yaml
      CodeUri: example/
      Events:
        StratusGet:
          Type: ALB
          Properties:
            Path: /stratus/test
            Method: GET
        StratusGetWithPathParam:
          Type: ALB
          Properties:
            Path: /stratus/123/endpoint
            Method: GET

