AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10
    MemorySize: 256

Resources:
  ServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: bootstrap
      CodeUri: example/
      Events:
        AlbEvent:
          Type: ALB
          Properties:
            Path: /health
            Method: GET
